### ISSUE TITLE
Newer version of pyglet installed with requirements is causes opengl error

### ISSUE THREAD

**Issue by jsim94** [DougTheDruid/SoT-ESP-Framework#16]
When installing requirements, pyglet 2.0.0 is installed due to no version specifications. Using 2.0.0 causes pyglet to throw 

  `pyglet.gl.lib.GLException:(0x502): Invalid operation. The specified operation is not allowed in the current state.`

when `main_batch.draw()` is called.

Rolling back to 1.5.27 fixed the issue.

**Comment by DougTheDruid** [comment]
https://github.com/DougTheDruid/SoT-ESP-Framework/commit/67339436f442bfcb8488151f03d2c593a380b429
